### ISSUE TITLE
No way to delete a single mark

### ISSUE THREAD

**Issue by paradox460** [colinta/SublimeMarkAndMove#2]
I often find I'm going through a file, leaving marks, when i inadvertently mark a place where I do not want a mark. There is no convenient way to delete said mark. mark_and_move_delete or some similar command would be very welcome

**Comment by eorroe** [comment]
I don't get this part:

> Then i can use sublime text's usual multi-cursor editing to remove that selection, mark again, and move on.

I don't know how you would explain this, but if you can please provide a gif.

Oh and yea I just found your package very useful thanks. But I too have this problem.

**Comment by colinta** [comment]
![mark-and-move](https://cloud.githubusercontent.com/assets/27570/6416816/2f9806d6-be66-11e4-92ae-59262d8e2e78.gif)

**Comment by colinta** [comment]
There's a handier trick, let me upload one more...

**Comment by colinta** [comment]
![mark-and-move](https://cloud.githubusercontent.com/assets/27570/6417478/d7c6b1c8-be6a-11e4-8f73-974e84586fea.gif)

**Comment by eorroe** [comment]
So are you using the mouse to deselect?

It's kind of weird to see. And if so I would have to disable dragging with mouse.

**Comment by eorroe** [comment]
I disabled drag text. Didn't work I'm confused what your doing with the mouse?

**Comment by colinta** [comment]
http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/editing/editing.html#using-the-mouse <http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/editing/editing.html#using-the-mouse>

**Comment by colinta** [comment]
You don’t need to disable drag text, either.

**Comment by eorroe** [comment]
Yea with mouse it doesn't work for me, keyboard version does.

It says for windows: alt + right mouse button + (up arrow?)

Yea man I'm sorry if I'm taking your time away from something. Answer whenever you want.

**Comment by colinta** [comment]
Sorry, no Windows knowledge.  You’ll need to google around.

**Comment by eorroe** [comment]
It says it on the link?

**Comment by colinta** [comment]
Sorry I can't help more.

**Comment by eorroe** [comment]
Alright thanks.

**Comment by eorroe** [comment]
I was looking through my packages to see if anything new came up, one thing I never suggested what if the `mark_and_move_save` actually just toggled on and off the mark, that would work and be intuitive.

**Comment by colinta** [comment]
That behavior currently triggers "select all and delete marks" - it selects all the marks, and clears the mark "buffer".  This feature is *exactly* what you can use to accomplish the goal of deleting marks, but is more versatile because it's easy to remove multiples, or to use Mark&Move as a "quick fix".

As an example, let's say you want to swap selections using `ctrl+t`.  You normally would need to use the mouse to make these selections, and maybe the two selections are far away (for instance, if you're reorganizing code, and want to swap the locations of two methods).

With Mark & Move:

1. Make the first selection and press `ctrl+m`
2. Make the second selection and press `ctrl+m` *twice*.
3. Press `ctrl+t`.  The selections are swapped and your mark buffer is clear.

If you messed up the second selection, the flow would look like this:

1. Make the first selection and press `ctrl+m`
2. Make the second selection and press `ctrl+m` *twice*.
3. Oops, second selection is wrong.  Use the mouse to *remove* that selection, leaving only the first selection.  Press `ctrl+m`
4. Make the correct selection and press `ctrl+m`

If you want to fork this project and change the behavior to work the way you described you have my blessing, but *I'm* not going to do it – it already works the way I want it to.
